import Head from "next/head";
import { useTranslation } from "@/hooks/useTranslation";

import { Header, AccordionHeader } from "@/components";

export default function Home() {
  const { textTranslated, setLanguage, language } = useTranslation();

  return (
    <>
      <Head>
        <title>Maincore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        textTranslated={textTranslated}
        setLanguage={setLanguage}
        language={language}
      />
      <AccordionHeader textTranslated={textTranslated} />
      <main>
        <section>
          <h1>teste</h1>
        </section>
      </main>
    </>
  );
}
