import { Title } from '@/styles/global.css'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Maincore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title> NextJS Blog with Butter CMS</Title>
    </>
  )
}
